In [16]:
import torch

In [23]:
#let's set up computation tracking 
a = torch.tensor(2.0, requires_grad=True)

In [26]:
y = 2*a**4 + a**3 + 3*a**2 + 5*a + 1
test_derivitive = 8*a**3+3*a**2+6*a+5 


In [27]:
print(y)
print(test_derivitive)

tensor(63., grad_fn=<AddBackward0>)
tensor(93., grad_fn=<AddBackward0>)


In [20]:
type(y)

torch.Tensor

In [21]:
y.backward()

In [22]:
a.grad

tensor(93.)

In [28]:
x = torch.tensor([[1.,2.,3.], [3.,2.,1.]], requires_grad=True)

In [29]:
print(x)

tensor([[1., 2., 3.],
        [3., 2., 1.]], requires_grad=True)


In [30]:
y = 3*x+2

In [31]:
print(y)

tensor([[ 5.,  8., 11.],
        [11.,  8.,  5.]], grad_fn=<AddBackward0>)


In [32]:
z = 2*y**2

In [33]:
print(z)

tensor([[ 50., 128., 242.],
        [242., 128.,  50.]], grad_fn=<MulBackward0>)


In [34]:
out = z.mean()

In [35]:
print(out)

tensor(140., grad_fn=<MeanBackward0>)


In [36]:
out.backward()

In [37]:
print(x.grad)

tensor([[10., 16., 22.],
        [22., 16., 10.]])
